config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users, only: [:show, :edit, :update]
  resources :menu_items
  resources :orders
  
  # 他のルート設定
  get 'admin/dashboard', to: 'admin#dashboard'
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  # ルートページの設定
  root 'orders#index'

  # adminページへのルート
  get 'admin', to: 'admin#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/menu_item.rb
class MenuItem < ApplicationRecord
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  belongs_to :menu_item
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  def dashboard
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/menu_items_controller.rb
class MenuItemsController < ApplicationController
  def index
  end

  def new
  end

  def create
  end

  def edit
  end

  def update
  end

  def destroy
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_menu_item, only: [:new, :create, :confirm]

  def new
    @order = Order.new
  end

  def create
    @order = Order.new(order_params)
    @order.user_id = current_user.id
    @order.menu_item_id = @menu_item.id

    if @order.quantity <= @menu_item.stock && @order.save
      @menu_item.stock -= @order.quantity
      @menu_item.save
      flash[:notice] = "注文が完了しました"
      redirect_to orders_path
    else
      flash[:alert] = "在庫が足りません"
      render :new
    end
  end

  def confirm
    @order = Order.new(order_params)
    @order.menu_item_id = @menu_item.id
    @subtotal = @menu_item.price * @order.quantity
  end

  private
  def set_menu_item
    @menu_item = MenuItem.find(params[:menu_item_id])
  end

  def order_params
    params.require(:order).permit(:quantity, :menu_item_id)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
  end

  def destroy
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
  end

  def edit
  end

  def update
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/menu_items_helper.rb
module MenuItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/dashboard.html.erb
<h1>Admin#dashboard</h1>
<p>Find me in app/views/admin/dashboard.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>4/2 ハママパスタ会</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>

    <style>
      html, body {
        height: 100%;
      }
      .menu-container {
        height: 100%;
        width: 100%;
        background-color: transparent; /* 背景色を透明にする */
      }
      main {
        margin-top: 0; /* main要素の上マージンを0にする */
        margin-bottom: 0;
      }
      body {
        display: flex;
        flex-direction: column;
      }
       header {
        background-color: black; /* header要素の背景色を黒色にする */
        color: white; /* header要素の文字色を白色にする */
        text-align: center;
       }
      footer {
        background-color: black; /* header要素の背景色を黒色にする */
        color: white; /* header要素の文字色を白色にする */
        text-align: center;
      }
    </style>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
     <link href="https://fonts.googleapis.com/css?family=Pacifico&display=swap" rel="stylesheet">
  </head>

 <body>
    <header>
  </header>

  <main>
      <%= yield %>
    </main>

    <footer>
     <%= link_to 'Admin Page', admin_path, class: 'btn btn-primary btn-admin' %>
      <p>&copy; <%= Time.now.year %> Hama Pasta Party. All rights reserved.</p>
    </footer>
 </body>
</html>

app/views/menu_items/create.html.erb
<h1>MenuItems#create</h1>
<p>Find me in app/views/menu_items/create.html.erb</p>

app/views/menu_items/destroy.html.erb
<h1>MenuItems#destroy</h1>
<p>Find me in app/views/menu_items/destroy.html.erb</p>

app/views/menu_items/edit.html.erb
<h1>MenuItems#edit</h1>
<p>Find me in app/views/menu_items/edit.html.erb</p>

app/views/menu_items/index.html.erb
<h1>MenuItems#index</h1>
<p>Find me in app/views/menu_items/index.html.erb</p>

app/views/menu_items/new.html.erb
<h1>MenuItems#new</h1>
<p>Find me in app/views/menu_items/new.html.erb</p>

app/views/menu_items/update.html.erb
<h1>MenuItems#update</h1>
<p>Find me in app/views/menu_items/update.html.erb</p>

app/views/orders/create.html.erb
<h1>Orders#create</h1>
<p>Find me in app/views/orders/create.html.erb</p>

app/views/orders/destroy.html.erb
<h1>Orders#destroy</h1>
<p>Find me in app/views/orders/destroy.html.erb</p>

app/views/orders/edit.html.erb
<h1>Orders#edit</h1>
<p>Find me in app/views/orders/edit.html.erb</p>

app/views/orders/index.html.erb
<div class="menu-container">
  <h1 class="menu-heading">MENU</h1>

  <div class="menu-items-container">
    <div class="menu-item">
      <h2 class="menu-item-heading">~pasta~</h2>
      <ul class="menu-item-list">
        <li>アラビアータ 500円<button class="menu-item-button"></li>
        <li>ハマビアータ~長ネギのアラビアータ(ニンニクなし)~ 500円<button class="menu-item-button">></li>
        <li>カルボナーラ 500円<button class="menu-item-button"></li>
        <li>ほうれん草と鶏ハムのクリームスパゲッティ 600円<button class="menu-item-button"></li>
        <li>ナポリタン 600円<button class="menu-item-button"></li>
      </ul>
    </div>
    <div class="menu-item">
      <h2 class="menu-item-heading">~Appetizers~</h2>
      <ul class="menu-item-list">
        <li>自家製モッツァレラチーズ ~バジルソースを添えて〜 500円<button class="menu-item-button"></li>
        <li>ホエイのしっとり鶏ハム 500円<button class="menu-item-button"></li>
        <li>ブロッコリーのあの、くたくた 500円<button class="menu-item-button"></li>
        <li>ジャガイモのフリコ 500円<button class="menu-item-button"></li>
      </ul>
    </div>
    <div class="menu-item">
      <h2 class="menu-item-heading">~Dessert~</h2>
      <ul class="menu-item-list">
        <li>あの、イタリアンプリン 400円<button class="menu-item-button"></li>
      </ul>
      <h2 class="menu-item-heading">~Special Drink~</h2>
      <ul class="menu-item-list">
        <li>ドルチェット・ダルバ DOC 2021</li>
        <li>グラス 800円</li>
        <li>ボトル 6000円</li>
        <li>レッドアイカクテル 100円</li>
      </ul>
    </div>
  </div>
</div>

app/views/orders/new.html.erb
<h1>Orders#new</h1>
<p>Find me in app/views/orders/new.html.erb</p>

app/views/orders/update.html.erb
<h1>Orders#update</h1>
<p>Find me in app/views/orders/update.html.erb</p>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>

app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>